# -------------------------------------------------------------------
# Configuration File — config/config.yaml
# -------------------------------------------------------------------
# Stores project-level configuration parameters for each pipeline stage.
# -------------------------------------------------------------------

data_ingestion:
  bucket_name: "mlops-hotel-reservation-prediction-bucket"    # GCP bucket name
  bucket_file_name: "Hotel_Reservations.csv"                  # Dataset file name
  train_ratio: 0.8                                            # Train/test split ratio